<?php
$pageTitle='Airport Flooring Solutions'; $pageDescription='Flooring planning for airport operational, service, logistics and public-facing areas.'; $bodyClass='industry-page industry-airports'; $assetPrefix='..'; require __DIR__.'/../includes/header.php'; $visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['Continuous traffic','Passenger, trolley and service movement place different demands across the facility.'],['Operational access','Work often needs phasing around live operations and restricted access windows.'],['Cleaning & appearance','Public-facing areas need maintainability as well as an appropriate visual finish.'],['Service zones','Back-of-house, baggage and utility areas can require more industrial floor approaches.']];
$zones=[['Terminal circulation','High footfall and trolley movement.'],['Baggage / service areas','Operational traffic and maintenance access.'],['Cargo / stores','Material handling and loading activity.'],['Plant / utility rooms','Technical service conditions and interfaces.'],['Commercial areas','Appearance, maintenance and public use.'],['Maintenance spaces','Workshop-type activity and local exposure.']];
$solutions=[['Epoxy Flooring','For suitable operational and support zones.','../services/epoxy-flooring.php'],['PU Flooring','For areas where service conditions call for a different resin approach.','../services/pu-flooring.php'],['VDF Flooring','For suitable concrete industrial/service areas.','../services/vdf-flooring.php'],['Waterproofing','Where water ingress or wet-interface detailing is part of the requirement.','../services/waterproofing.php']];
?>
<main class="industry-main" id="main-content"><section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Airports</span><h1>Airport <em>Floors</em></h1><p>Airport environments combine high public traffic, operational zones, logistics, utilities and strict access windows. Flooring needs to be planned by area and use.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on area use, substrate condition and project requirements.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Operational planning</span><strong>Traffic pattern, maintenance need and access window guide the recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">One airport contains many floor environments.</h2></div><div class="industry-copy"><p class="industry-definition">Terminal, baggage, cargo, commercial and service areas should not be treated as one flooring condition.</p><p>We review traffic, cleaning, appearance, substrate condition and execution access for each zone.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">What affects the floor decision.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">Different zones. Different demands.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Systems to evaluate after assessment.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">05 / Site visit</span><h2 class="section-title">Assess the zone before choosing the floor.</h2></div><div><p>Share the area type, traffic pattern, current floor and available work window.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section></main><?php require __DIR__.'/../includes/footer.php'; ?>