<?php
$pageTitle='Commercial Space Flooring Solutions'; $pageDescription='Flooring planning for retail, office, institutional and other commercial environments.'; $bodyClass='industry-page industry-commercial-spaces'; $assetPrefix='..'; require __DIR__.'/../includes/header.php'; $visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['Appearance & use','The floor needs to support the visual brief as well as day-to-day use.'],['Cleaning routine','Finish selection should consider how the space is cleaned and maintained.'],['Public traffic','Footfall, trolleys or furniture movement influence durability requirements.'],['Renovation access','Existing businesses may require phased work and controlled shutdown periods.']];
$zones=[['Retail floors','Customer traffic, display zones and maintenance.'],['Office / common areas','Appearance, foot traffic and cleaning.'],['Back-of-house','Service activity and practical maintenance.'],['Entrances / corridors','Repeated traffic and transition details.'],['Utility areas','Local service conditions and substrate needs.'],['Institutional spaces','Daily use, maintenance and appearance.']];
$solutions=[['Epoxy Flooring','A seamless resin-floor concept for suitable commercial applications.','../services/epoxy-flooring.php'],['PU Flooring','An alternative resin system to evaluate around service conditions.','../services/pu-flooring.php'],['PVC Flooring','For projects where resilient sheet/tile flooring is part of the requirement.','../services/pvc-flooring.php'],['Waterproofing','For areas affected by water ingress or wet interfaces.','../services/waterproofing.php']];
?>
<main class="industry-main" id="main-content"><section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Commercial Spaces</span><h1>Commercial <em>Floors</em></h1><p>Commercial flooring has to balance appearance, cleaning, public use, maintenance and installation access without treating every space the same.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on use, substrate condition and project requirements.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Use-led selection</span><strong>Traffic, visual requirement, cleaning and access guide the floor recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Space need</span><h2 class="section-title">The customer area and service area are different floor problems.</h2></div><div class="industry-copy"><p class="industry-definition">A public-facing retail floor may prioritize appearance and cleanability, while a back-of-house zone may need a more practical service finish.</p><p>We assess each area according to use, traffic and maintenance expectations.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">What needs to be balanced.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Space types</span><h2 class="section-title">Different areas. Different expectations.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Systems to evaluate after inspection.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">05 / Site visit</span><h2 class="section-title">Understand the space before selecting the finish.</h2></div><div><p>Share the space type, current floor, traffic and desired maintenance approach.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section></main><?php require __DIR__.'/../includes/footer.php'; ?>