<?php
$pageTitle = 'Data Centre Flooring Solutions';
$pageDescription = 'Flooring solutions for data centres and technical spaces, selected around static-control requirements, cleaning, equipment zones, substrate condition and project specifications.';
$bodyClass = 'industry-page industry-data-centres';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$challenges = [['Static-control requirements','Some technical areas may require a defined ESD or antistatic flooring strategy that must be specified and tested for the project.'],['Equipment and service zones','Rack, UPS, battery, support and access areas can have different operational requirements.'],['Cleanliness and maintenance','Dust control, cleaning routines and surface condition can influence flooring selection.'],['Critical operations','Execution planning needs to consider access, isolation and the sensitivity of live technical environments.']];
$zones = [['White space / equipment halls','Static-control and maintenance requirements may be central to system selection.'],['UPS / electrical rooms','Electrical-area requirements and project specifications need careful review.'],['Battery / utility areas','Operating exposure and maintenance routines can differ from main technical spaces.'],['Control / support rooms','Traffic, cleanliness and surface finish may drive the approach.'],['Access corridors','Repeated movement and maintenance access should be considered.'],['Raised-floor / transition areas','Interfaces and compatibility with surrounding systems require project-specific detailing.']];
$solutions = [['ESD / Antistatic Flooring','For projects that require a defined static-control flooring system and verification approach.','../services/esd-flooring.php'],['Dielectric Flooring','For selected electrical areas where an insulating-floor requirement is specified for the project.','../services/dielectric-flooring.php'],['Epoxy Flooring','For support or technical areas where a resin-floor finish is suitable after assessment.','../services/epoxy-flooring.php']];
?>
<main class="industry-main" id="main-content">
<section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Data Centres</span><h1>Data Centre <em>Floors</em></h1><p>Technical spaces need flooring decisions that reflect static-control requirements, equipment zones, maintenance, cleanliness and the project specification—not a generic industrial coating.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="industry-hero-note">Any ESD, antistatic or dielectric performance requirement must be defined and verified for the specific project.</p></div><div class="industry-hero-media" role="img" aria-label="Industrial flooring project source photograph"><div class="industry-hero-badge"><span>Specification-led</span><strong>Static control, insulation, equipment use and maintenance requirements should be reviewed before system selection.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility requirement</span><h2 class="section-title">Technical spaces need a more disciplined flooring brief.</h2></div><div class="industry-copy"><p class="industry-definition">The flooring approach should begin with the technical requirement for each room, including whether static-control or insulating performance is actually required.</p><p>Substrate condition, equipment layout, access, cleaning and operational sensitivity all need to be understood before the final system is specified.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">Performance requirements differ across technical zones.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]): ?><article class="industry-challenge"><span><?= sprintf('%02d',$i+1) ?></span><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Areas within the facility</span><h2 class="section-title">Separate the requirement by room and equipment use.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]): ?><div class="industry-zone"><strong><?= site_escape($t) ?></strong><span><?= site_escape($d) ?></span></div><?php endforeach; ?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Choose the system from the technical brief.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]): ?><article class="industry-solution"><span><?= sprintf('%02d',$i+1) ?></span><div><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></div><a href="<?= site_escape($u) ?>">Explore <?= $arrow ?></a></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Assessment</span><h2 class="section-title">Define the required performance before choosing the floor.</h2><p class="section-description">We review the project specification, room function, substrate, equipment zones, access and testing expectations before discussing the system build-up.</p></div><div class="industry-assessment-steps"><article class="industry-assessment-step"><span>01</span><div><strong>Requirement review</strong><p>Identify whether the area needs standard resin flooring, ESD control or dielectric performance.</p></div></article><article class="industry-assessment-step"><span>02</span><div><strong>Substrate and interfaces</strong><p>Inspect the floor condition and transitions around equipment or raised-floor systems.</p></div></article><article class="industry-assessment-step"><span>03</span><div><strong>Testing / handover plan</strong><p>Agree project-specific verification where electrical or static-control performance is required.</p></div></article></div></div></section>
<section class="section industry-execution"><div class="container"><span class="section-eyebrow">06 / Execution</span><h2 class="section-title">Control the process in sensitive technical areas.</h2><div class="industry-process-grid"><article class="industry-process-item"><span>01</span><strong>Review</strong><p>Confirm room and performance requirements.</p></article><article class="industry-process-item"><span>02</span><strong>Prepare</strong><p>Prepare the substrate to the agreed method.</p></article><article class="industry-process-item"><span>03</span><strong>Install</strong><p>Apply the selected system with controlled access.</p></article><article class="industry-process-item"><span>04</span><strong>Verify</strong><p>Carry out agreed project-specific checks.</p></article><article class="industry-process-item"><span>05</span><strong>Handover</strong><p>Document care and relevant support requirements.</p></article></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">07 / Start with the requirement</span><h2 class="section-title">Share the technical brief before selecting the flooring system.</h2></div><div><p>Tell us the room type, required performance, current floor condition and execution constraints. We can then determine the right assessment path.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>