<?php
$pageTitle='Defence Facility Flooring Solutions'; $pageDescription='Requirement-led flooring and surface-protection planning for defence workshops, stores, laboratories, utilities and support facilities.'; $bodyClass='industry-page industry-defence'; $assetPrefix='..'; require __DIR__.'/../includes/header.php'; $visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['Controlled requirements','Some areas may have project-specific electrical, chemical, hygiene or access requirements.'],['Heavy service use','Workshops, stores and maintenance zones can experience concentrated wear and movement.'],['Restricted access','Execution planning may need to accommodate security, permits and limited work windows.'],['Mixed facility types','Technical rooms, stores, offices and workshops should be assessed separately.']];
$zones=[['Workshops','Maintenance activity, traffic and local exposure.'],['Stores / logistics','Material movement, pallets and handling routes.'],['Technical rooms','Project-specific electrical and service requirements.'],['Laboratories','Cleaning, exposure and controlled-area needs.'],['Utilities','Plant and service-space floor conditions.'],['Administrative areas','Appearance, maintenance and daily use.']];
$solutions=[['Epoxy Flooring','For suitable industrial and controlled support areas.','../services/epoxy-flooring.php'],['PU Flooring','For environments where service conditions support a PU system.','../services/pu-flooring.php'],['ESD Flooring','Where a defined static-control requirement forms part of the specification.','../services/esd-flooring.php'],['Dielectric Flooring','Where an approved electrical-insulation requirement is specified for the area.','../services/dielectric-flooring.php'],['VDF Flooring','For suitable hard-wearing concrete industrial zones.','../services/vdf-flooring.php']];
?>
<main class="industry-main" id="main-content"><section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Defence</span><h1>Defence <em>Facilities</em></h1><p>Defence facilities can combine workshops, stores, laboratories, technical rooms and controlled support areas. The floor system should follow the actual area specification.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Project security, access and technical criteria must be confirmed before system selection.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Specification-led approach</span><strong>Area function, substrate, access and approved technical criteria guide the recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">The requirement comes from the area, not the industry label.</h2></div><div class="industry-copy"><p class="industry-definition">A workshop, technical room and laboratory can demand very different flooring performance.</p><p>We review the area use, existing floor, exposure, movement and project-specific criteria before discussing a system.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">Conditions that shape the flooring approach.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">Different zones. Different specifications.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Systems to evaluate against the approved requirement.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Technical control</span><h2 class="section-title">Do not generalize measurable performance.</h2><p class="section-description">Electrical, chemical, static-control or other measurable requirements should be taken from the approved project specification and matched to verified system data.</p></div><div class="industry-note">No universal resistance, dielectric, thickness or compliance value is published on this page because those values depend on the specific approved system and project requirement.</div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">06 / Site review</span><h2 class="section-title">Start with the area requirement and access conditions.</h2></div><div><p>Share the facility zone, current floor and approved technical requirement where available.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section></main><?php require __DIR__.'/../includes/footer.php'; ?>