<?php
$pageTitle='Educational Institution Flooring Solutions'; $pageDescription='Flooring planning for schools, colleges, laboratories, corridors, utility and institutional spaces.'; $bodyClass='industry-page industry-education'; $assetPrefix='..'; require __DIR__.'/../includes/header.php'; $visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['High footfall','Corridors, classrooms and common areas experience repeated daily traffic.'],['Cleaning & maintenance','Finish selection should support practical routine cleaning and upkeep.'],['Mixed-use spaces','Laboratories, classrooms, workshops and public areas can need different approaches.'],['Holiday / shutdown windows','Execution may need to be planned around academic schedules and limited access periods.']];
$zones=[['Classrooms','Daily foot traffic and practical maintenance.'],['Corridors / common areas','High repeated movement and transitions.'],['Laboratories','Cleaning, local exposure and technical requirements.'],['Workshops','More industrial use and local wear.'],['Utility / wash areas','Wet interfaces and substrate condition.'],['Administrative areas','Appearance, comfort and maintenance.']];
$solutions=[['Epoxy Flooring','For suitable institutional, laboratory and service spaces.','../services/epoxy-flooring.php'],['PU Flooring','For areas where service conditions support a PU system.','../services/pu-flooring.php'],['PVC Flooring','For projects requiring resilient flooring in selected interior areas.','../services/pvc-flooring.php'],['Waterproofing','For wet areas and water-ingress related requirements.','../services/waterproofing.php']];
?>
<main class="industry-main" id="main-content"><section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Education</span><h1>Institutional <em>Floors</em></h1><p>Educational facilities combine high-traffic public areas with classrooms, laboratories, workshops and utilities. Flooring should be selected by area and use.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on site condition, use and project requirements.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Practical planning</span><strong>Traffic, cleaning, room use and academic access windows guide the recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">A campus contains more than one floor condition.</h2></div><div class="industry-copy"><p class="industry-definition">A corridor, laboratory and workshop should not automatically receive the same flooring solution.</p><p>We consider traffic, cleaning, room function, existing substrate and available execution window.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">What affects the floor decision.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">Different rooms. Different demands.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Options to evaluate after inspection.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">05 / Site visit</span><h2 class="section-title">Assess the area before selecting the floor.</h2></div><div><p>Share the room type, current floor, traffic and available execution period.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section></main><?php require __DIR__.'/../includes/footer.php'; ?>