<?php
$pageTitle = 'Hospital & Healthcare Flooring Solutions';
$pageDescription = 'Flooring and wall-surface solutions for hospitals and healthcare environments, selected around cleaning, traffic, interfaces and operational requirements.';
$bodyClass = 'industry-page industry-healthcare';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$challenges = [['Cleaning and hygiene routines','Surface continuity, joints and floor-to-wall details can affect how an area is maintained.'],['Continuous traffic','Corridors, service routes and support areas may see regular trolley and pedestrian movement.'],['Different clinical/support zones','Treatment, utility, laboratory and public areas can have different requirements.'],['Operational access','Work may need careful phasing around occupied or sensitive areas.']];
$zones = [['Clinical support areas','Cleaning, traffic and finish requirements should be reviewed.'],['Laboratory / diagnostic areas','Operational exposure and project-specific surface requirements may differ.'],['Corridors and circulation','Repeated pedestrian and trolley traffic influences the approach.'],['Utility / service areas','Practical maintenance and durability may take priority.'],['Controlled rooms','Interfaces, cleaning and project documentation require closer assessment.'],['Public / support spaces','Appearance, maintenance and daily use need to be balanced.']];
$solutions = [['Epoxy Flooring','A seamless resin-floor concept that may be considered where the substrate and area requirements are suitable.','../services/epoxy-flooring.php'],['PU Flooring','A possible alternative resin-system route depending on operating exposure and project specification.','../services/pu-flooring.php'],['Clean Room Wall Coating','For selected controlled or hygiene-focused areas where wall-surface continuity is part of the project scope.','../services/clean-room-wall-coating.php']];
?>
<main class="industry-main" id="main-content">
<section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Hospitals & Healthcare</span><h1>Healthcare <em>Surfaces</em></h1><p>Healthcare environments need flooring and wall-surface decisions that consider cleaning, traffic, interfaces, operational sensitivity and the requirements of each area.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="industry-hero-note">Final system selection depends on the room use, substrate and project-specific requirements.</p></div><div class="industry-hero-media" role="img" aria-label="Flooring project source photograph"><div class="industry-hero-badge"><span>Environment first</span><strong>Clinical, circulation, laboratory and utility areas should not automatically receive the same system.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility requirement</span><h2 class="section-title">Cleaning, traffic and room use should guide the flooring decision.</h2></div><div class="industry-copy"><p class="industry-definition">A healthcare project is best approached by understanding how each space is operated and maintained before discussing a flooring or wall system.</p><p>Floor-to-wall details, cleaning routines, existing surfaces, access restrictions and occupied-area planning can all influence the recommendation.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">Surface requirements change across the facility.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]): ?><article class="industry-challenge"><span><?= sprintf('%02d',$i+1) ?></span><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Areas within the facility</span><h2 class="section-title">Assess the room, not just the building type.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]): ?><div class="industry-zone"><strong><?= site_escape($t) ?></strong><span><?= site_escape($d) ?></span></div><?php endforeach; ?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Select the system around the actual area requirement.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]): ?><article class="industry-solution"><span><?= sprintf('%02d',$i+1) ?></span><div><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></div><a href="<?= site_escape($u) ?>">Explore <?= $arrow ?></a></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Assessment</span><h2 class="section-title">Review room use, interfaces and execution constraints.</h2><p class="section-description">The assessment should cover the existing floor, cleaning routine, traffic, floor-to-wall transitions and how work can be isolated from surrounding operations.</p></div><div class="industry-assessment-steps"><article class="industry-assessment-step"><span>01</span><div><strong>Area classification</strong><p>Understand the room function and operating sensitivity.</p></div></article><article class="industry-assessment-step"><span>02</span><div><strong>Surface review</strong><p>Inspect substrate condition, interfaces and existing finishes.</p></div></article><article class="industry-assessment-step"><span>03</span><div><strong>Execution planning</strong><p>Plan access, isolation and handover around facility operations.</p></div></article></div></div></section>
<section class="section industry-execution"><div class="container"><span class="section-eyebrow">06 / Execution</span><h2 class="section-title">Control the work from preparation through handover.</h2><div class="industry-process-grid"><article class="industry-process-item"><span>01</span><strong>Survey</strong><p>Review room use and surfaces.</p></article><article class="industry-process-item"><span>02</span><strong>Detailing</strong><p>Confirm interfaces and project scope.</p></article><article class="industry-process-item"><span>03</span><strong>Preparation</strong><p>Prepare surfaces to the agreed method.</p></article><article class="industry-process-item"><span>04</span><strong>Application</strong><p>Execute the selected system with area controls.</p></article><article class="industry-process-item"><span>05</span><strong>Handover</strong><p>Inspect and discuss care requirements.</p></article></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">07 / Start with the area</span><h2 class="section-title">Let us understand the healthcare space before recommending the surface.</h2></div><div><p>Share the room type, current floor or wall condition, approximate area and available execution window. We can then discuss the appropriate assessment.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>