<?php
$pageTitle='Laboratory Flooring Solutions';
$pageDescription='Flooring and surface-protection planning for laboratories, testing areas and controlled technical spaces.';
$bodyClass='industry-page industry-laboratories'; $assetPrefix='..'; require __DIR__.'/../includes/header.php';
$visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['Cleaning & contamination control','Floor and wall finishes should support the facility cleaning routine.'],['Chemical exposure','Reagents, cleaning agents and process exposure vary by laboratory and must be reviewed.'],['Joints & interfaces','Floor-to-wall, drain, threshold and equipment interfaces affect maintainability.'],['Operational access','Work may need to be planned around active rooms, instruments and shutdown windows.']];
$zones=[['Testing laboratories','Finish, cleaning and local exposure requirements.'],['Sample preparation','Spill risk, movement and cleaning routines.'],['Instrument rooms','Equipment access, service routes and project-specific static requirements.'],['Wash / utility areas','Wet-use interfaces, drainage and substrate condition.'],['Corridors & support areas','Foot traffic, trolley movement and maintenance.'],['Controlled rooms','Project-specific cleanliness and detailing requirements.']];
$solutions=[['Epoxy Flooring','A seamless resin-floor concept where the substrate and use are suitable.','../services/epoxy-flooring.php'],['PU Flooring','A resin-flooring option to assess where service conditions call for it.','../services/pu-flooring.php'],['ESD Flooring','For areas with defined static-control requirements and approved electrical criteria.','../services/esd-flooring.php'],['Clean Room Wall Coating','For wall-finish requirements in controlled technical environments.','../services/clean-room-wall-coating.php']];
?>
<main class="industry-main" id="main-content">
<section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Laboratories</span><h1>Laboratory <em>Floors</em></h1><p>Laboratory floors need to be considered around cleaning, local chemical exposure, equipment interfaces and the way the room is actually operated.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on site conditions, operating exposure and technical assessment.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Requirement-led selection</span><strong>Room use, substrate, cleaning and interfaces guide the recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">The laboratory type changes the floor requirement.</h2></div><div class="industry-copy"><p class="industry-definition">A testing lab, sample-preparation room, instrument area and wash zone can place very different demands on the same flooring system.</p><p>We therefore start with the room function and site condition rather than prescribing one material across the facility.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">What needs to be understood first.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">One facility. Different operating zones.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Systems to evaluate after assessment.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Assessment</span><h2 class="section-title">Inspect before specifying.</h2><p class="section-description">Review substrate condition, moisture, room use, cleaning, exposure, transitions and shutdown availability before selecting the floor system.</p></div><div class="industry-note">Where static control, chemical performance or other measurable criteria are required, the project specification and approved system data should define the acceptance values.</div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">06 / Site visit</span><h2 class="section-title">Let us understand the laboratory before recommending the floor.</h2></div><div><p>Share the room type, current floor condition, operating exposure and available shutdown window.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section>
</main>
<?php require __DIR__.'/../includes/footer.php'; ?>