<?php
$pageTitle='Seaport Flooring Solutions'; $pageDescription='Flooring and surface-protection planning for port logistics, service, warehouse and utility areas.'; $bodyClass='industry-page industry-seaports'; $assetPrefix='..'; require __DIR__.'/../includes/header.php'; $visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['Heavy movement','Material handling, trolleys and service traffic affect floor wear and detailing.'],['Moisture exposure','Open or semi-open areas may face wet conditions that need to be understood.'],['Operational continuity','Work frequently needs coordination around live logistics activity.'],['Mixed environments','Warehouses, workshops, offices and utilities can require different systems.']];
$zones=[['Warehouses','Material movement, storage and loading.'],['Workshops','Maintenance activity and local exposure.'],['Loading / service zones','Traffic, moisture and edge conditions.'],['Utility rooms','Technical service requirements.'],['Administrative areas','Appearance, maintenance and daily use.'],['Covered circulation','Repeated trolley and personnel movement.']];
$solutions=[['Epoxy Flooring','For suitable enclosed service and support areas.','../services/epoxy-flooring.php'],['PU Flooring','For project areas where the operating environment supports its use.','../services/pu-flooring.php'],['VDF Flooring','For suitable concrete industrial and logistics zones.','../services/vdf-flooring.php'],['Waterproofing','Where water ingress or wet-area detailing must be addressed.','../services/waterproofing.php']];
?>
<main class="industry-main" id="main-content"><section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Seaports</span><h1>Seaport <em>Floors</em></h1><p>Port facilities combine logistics, storage, workshops, utilities and wet exposure. Flooring needs to be matched to each operating zone.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on substrate, exposure, traffic and project requirements.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Zone-specific planning</span><strong>Traffic, moisture and operational access guide the recommendation.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">Port operations create varied floor conditions.</h2></div><div class="industry-copy"><p class="industry-definition">A warehouse floor, workshop and wet service zone can require very different surface strategies.</p><p>We review traffic, exposure, substrate condition and access before discussing the system.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">Conditions that influence the decision.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">Different zones. Different demands.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Options to evaluate after inspection.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">05 / Site visit</span><h2 class="section-title">Assess the operating zone before choosing the floor.</h2></div><div><p>Share the area type, exposure, traffic and current floor condition.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section></main><?php require __DIR__.'/../includes/footer.php'; ?>