<?php
$pageTitle='Textile Industry Flooring Solutions';
$pageDescription='Flooring planning for textile production, dyeing, utility, storage and movement areas.';
$bodyClass='industry-page industry-textiles'; $assetPrefix='..'; require __DIR__.'/../includes/header.php';
$visitUrl=site_escape(site_url('schedule-visit.php'));
$challenges=[['High traffic','Trolleys, material movement and repeated foot traffic influence the required finish.'],['Wet / process zones','Dyeing, washing or utility areas may need different treatment from dry production zones.'],['Dust & fibres','Cleaning requirements and airborne fibres should be considered when selecting the surface.'],['Shutdown planning','Installation needs to be coordinated around production schedules and area availability.']];
$zones=[['Production floors','Machine areas, operator movement and cleaning.'],['Dyeing / process areas','Wet use, local exposure and drainage interfaces.'],['Stores & dispatch','Material movement, pallets and traffic routes.'],['Utilities','Service spaces with different exposure conditions.'],['Quality / inspection','Cleanability and visual finish requirements.'],['Circulation areas','Foot traffic, trolley movement and maintenance.']];
$solutions=[['Epoxy Flooring','For suitable dry or controlled production and support areas.','../services/epoxy-flooring.php'],['PU Flooring','To assess where service conditions and exposure make it appropriate.','../services/pu-flooring.php'],['VDF Flooring','For concrete-floor applications where hard-wearing industrial use is part of the requirement.','../services/vdf-flooring.php'],['Waterproofing','For areas where water ingress or wet-use detailing needs to be addressed.','../services/waterproofing.php']];
?>
<main class="industry-main" id="main-content">
<section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Textiles</span><h1>Textile <em>Floors</em></h1><p>Textile facilities combine production, material movement, wet-process zones, storage and inspection areas. Each zone can require a different flooring approach.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div><p class="industry-hero-note">Final system selection depends on actual floor condition and operating environment.</p></div><div class="industry-hero-media"><div class="industry-hero-badge"><span>Zone-based planning</span><strong>Production, wet process, storage and circulation areas should be assessed separately.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility need</span><h2 class="section-title">The process zone changes the requirement.</h2></div><div class="industry-copy"><p class="industry-definition">A dry production line and a wet processing area should not automatically receive the same floor system.</p><p>Traffic, cleaning, moisture, process exposure and shutdown access all influence the recommendation.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">Operational conditions to assess.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]):?><article class="industry-challenge"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Facility areas</span><h2 class="section-title">Different zones. Different demands.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]):?><div class="industry-zone"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Options to evaluate after inspection.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]):?><article class="industry-solution"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div><a href="<?=site_escape($u)?>">Explore →</a></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Assessment</span><h2 class="section-title">Plan around the production floor.</h2><p class="section-description">Inspect the substrate, identify wet and dry zones, understand traffic and cleaning, then plan execution around production access.</p></div><div class="industry-note">System performance and finish should be matched to the actual textile process area rather than generalized across the full plant.</div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">06 / Site visit</span><h2 class="section-title">Let us map the facility before recommending the floor.</h2></div><div><p>Share the area type, process condition, existing floor and shutdown availability.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit</a></div></div></div></section>
</main>
<?php require __DIR__.'/../includes/footer.php'; ?>