<?php
$pageTitle = 'Warehouse & Logistics Flooring Solutions';
$pageDescription = 'Flooring solutions for warehouses, dispatch areas and logistics facilities, selected around traffic, handling routes, cleaning and slab condition.';
$bodyClass = 'industry-page industry-warehouses';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$challenges = [['Forklift and pallet traffic','Repeated wheel paths can create concentrated wear and reveal slab defects.'],['Dusting or worn concrete','Surface deterioration can affect cleanliness, appearance and handling areas.'],['Large operational areas','Execution often needs phasing around live warehouse movement and access.'],['Loading / dispatch exposure','Entrances and loading zones may experience different traffic and environmental conditions.']];
$zones = [['Main storage aisles','Traffic intensity and existing slab condition influence the recommendation.'],['Picking / packing','Cleanliness, movement and maintenance routines can matter.'],['Loading bays','Transitions, impact and external exposure should be considered.'],['Dispatch zones','Repeated vehicle and material movement can create localized wear.'],['Utility / charging areas','Operational exposure may require a different flooring approach.'],['Walkways / marked routes','Visual organization can be considered alongside floor performance.']];
$solutions = [['Epoxy Flooring','A possible resin-floor option where the substrate and operating conditions are suitable.','../services/epoxy-flooring.php'],['PU Flooring','For selected areas where operating exposure or project requirements call for a different resin system.','../services/pu-flooring.php'],['VDF Flooring','A possible route for new or selected heavy-use concrete-floor applications.','../services/vdf-flooring.php']];
?>
<main class="industry-main" id="main-content">
<section class="industry-hero"><div class="container-wide industry-hero-grid"><div class="industry-hero-copy"><span class="industry-kicker">Industry / Warehouses & Logistics</span><h1>Warehouse <em>Flooring</em></h1><p>Warehouse floors work as part of the material-flow system. Traffic, wheel paths, slab condition, cleanliness and operational continuity all need to be considered together.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="industry-hero-note">Final flooring selection depends on site conditions and technical assessment.</p></div><div class="industry-hero-media" role="img" aria-label="Industrial flooring project source photograph"><div class="industry-hero-badge"><span>Material movement matters</span><strong>Traffic routes, loading zones and operational access can shape the flooring approach.</strong></div></div></div></section>
<section class="section"><div class="container industry-intro-grid"><div><span class="section-eyebrow">01 / Facility requirement</span><h2 class="section-title">The floor supports every movement through the warehouse.</h2></div><div class="industry-copy"><p class="industry-definition">A warehouse recommendation should start with the slab, traffic pattern and operating routine rather than with a generic coating specification.</p><p>Forklift routes, loading areas, existing damage, dusting and available execution windows can all change the solution.</p></div></div></section>
<section class="section industry-challenges"><div class="container"><span class="section-eyebrow">02 / Common challenges</span><h2 class="section-title">High-use routes reveal problems quickly.</h2><div class="industry-challenge-grid"><?php foreach($challenges as $i=>[$t,$d]): ?><article class="industry-challenge"><span><?= sprintf('%02d',$i+1) ?></span><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><span class="section-eyebrow">03 / Areas within the facility</span><h2 class="section-title">Not every logistics zone sees the same demand.</h2><div class="industry-zone-grid"><?php foreach($zones as [$t,$d]): ?><div class="industry-zone"><strong><?= site_escape($t) ?></strong><span><?= site_escape($d) ?></span></div><?php endforeach; ?></div></div></section>
<section class="section industry-solutions"><div class="container"><span class="section-eyebrow">04 / Solution routes</span><h2 class="section-title">Match the system to the traffic and substrate.</h2><div class="industry-solution-list"><?php foreach($solutions as $i=>[$t,$d,$u]): ?><article class="industry-solution"><span><?= sprintf('%02d',$i+1) ?></span><div><h3><?= site_escape($t) ?></h3><p><?= site_escape($d) ?></p></div><a href="<?= site_escape($u) ?>">Explore <?= $arrow ?></a></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container industry-assessment-grid"><div><span class="section-eyebrow">05 / Assessment</span><h2 class="section-title">Map the traffic before recommending the floor.</h2><p class="section-description">We review the existing slab, movement routes, wear, contamination and operational constraints before discussing a flooring system.</p></div><div class="industry-assessment-steps"><article class="industry-assessment-step"><span>01</span><div><strong>Slab condition</strong><p>Review cracks, dusting, repairs and existing finishes.</p></div></article><article class="industry-assessment-step"><span>02</span><div><strong>Traffic mapping</strong><p>Understand forklift, pallet and pedestrian movement.</p></div></article><article class="industry-assessment-step"><span>03</span><div><strong>Phasing plan</strong><p>Coordinate work with access, dispatch and shutdown requirements.</p></div></article></div></div></section>
<section class="section industry-execution"><div class="container"><span class="section-eyebrow">06 / Execution</span><h2 class="section-title">Plan the work around warehouse continuity.</h2><div class="industry-process-grid"><article class="industry-process-item"><span>01</span><strong>Survey</strong><p>Review slab and traffic patterns.</p></article><article class="industry-process-item"><span>02</span><strong>Zone plan</strong><p>Define sequence and access requirements.</p></article><article class="industry-process-item"><span>03</span><strong>Preparation</strong><p>Prepare and repair the agreed areas.</p></article><article class="industry-process-item"><span>04</span><strong>Application</strong><p>Install the selected system in planned phases.</p></article><article class="industry-process-item"><span>05</span><strong>Handover</strong><p>Inspect and discuss care requirements.</p></article></div></div></section>
<section class="section industry-final"><div class="container industry-final-grid"><div><span class="section-eyebrow">07 / Start with the site</span><h2 class="section-title">Let us review your traffic routes and floor condition.</h2></div><div><p>Share the warehouse layout, approximate area, current floor problems and available work windows. We can then plan the next assessment step.</p><div class="industry-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>