<?php
$pageTitle = 'PVC Flooring Solutions';
$pageDescription = 'Explore PVC flooring for commercial, institutional and controlled-use environments. Selection depends on traffic, cleaning, substrate condition and project requirements.';
$bodyClass = 'service-page service-pvc';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$problems=[['Damaged finish','Wear, lifting, joints and substrate defects should be reviewed before replacement or new installation.'],['Cleaning requirement','The required cleaning routine and room use influence the appropriate flooring type and finish.'],['Traffic pattern','Foot traffic, trolleys, furniture and equipment movement should be understood before selection.'],['Substrate condition','Flatness, moisture and existing floor build-up can affect preparation and installation.']];
$benefits=[['Practical finish options','PVC flooring can be considered where a resilient finished surface suits the room use and maintenance plan.'],['Defined visual finish','Colour and finish selection can support wayfinding, zoning or interior requirements where appropriate.'],['Room-by-room planning','Different areas can be reviewed according to use, traffic, hygiene expectations and cleaning routine.'],['Replacement planning','Existing floor removal, repairs and installation sequencing can be planned around access and shutdown needs.']];
$suitability=[['Hospitals & healthcare','Where room use, cleaning and traffic need to be balanced.'],['Laboratories','Where a resilient floor may be considered after reviewing the technical room requirements.'],['Commercial spaces','Where appearance, comfort and maintainability are important.'],['Educational facilities','Where daily traffic and maintenance influence flooring selection.'],['Offices / support areas','Where resilient flooring may suit occupied interior spaces.'],['Controlled-use rooms','Where flooring must be selected around the specific operational requirement.']];
$assessment=[['Room use','Understand occupants, traffic, equipment, cleaning and expected wear.'],['Substrate','Check flatness, moisture, damage and existing floor layers.'],['Flooring format','Review the appropriate PVC format, finish and detailing for the project.'],['Installation planning','Coordinate preparation, access, sequencing and handover around the facility schedule.']];
$process=[['01','Site review','Understand the room use, traffic and current floor.'],['02','Substrate preparation','Prepare and repair the floor to suit the selected installation method.'],['03','Layout planning','Confirm orientation, joints, edges and room transitions.'],['04','Installation','Install the selected PVC flooring under controlled site conditions.'],['05','Handover','Review finish, edges and project-specific care guidance.']];
?>
<main class="service-main" id="main-content">
<section class="service-hero" aria-labelledby="service-title"><div class="container-wide service-hero-grid"><div class="service-hero-copy"><span class="service-kicker">Flooring Solution / PVC</span><h1 id="service-title">PVC <em>Flooring</em></h1><p>A resilient flooring option for selected commercial, institutional and controlled-use spaces, planned around room function, traffic, cleaning and substrate condition.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="service-hero-note">Final flooring type, detailing and installation method depend on the room requirement and existing substrate.</p></div><div class="service-hero-media service-technical-media" role="img" aria-label="Technical resilient flooring concept visual"><div class="service-hero-badge"><span>Room use matters</span><strong>Traffic, cleaning, substrate and edge detailing guide the selection.</strong></div></div></div></section>
<section class="section" aria-labelledby="what-is-pvc"><div class="container service-intro-grid"><div><span class="section-eyebrow">01 / What it is</span><h2 class="section-title" id="what-is-pvc">A resilient floor selected around how the room is used.</h2></div><div class="service-copy"><p class="service-definition">PVC flooring is best approached as a <strong>room-specific finish system</strong>, not a universal answer for every facility.</p><p>Traffic, cleaning, furniture and equipment movement, substrate condition and required appearance all influence the appropriate product and installation method.</p><p>Transitions, edges and adjoining floor finishes should also be considered during planning.</p></div></div></section>
<section class="section service-problems" aria-labelledby="pvc-problems"><div class="container"><span class="section-eyebrow">02 / What to assess</span><h2 class="section-title" id="pvc-problems">The room requirement comes before the finish choice.</h2><div class="service-problem-grid"><?php foreach($problems as $i=>[$t,$d]):?><article class="service-problem"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="pvc-benefits"><div class="container"><span class="section-eyebrow">03 / Why it may be considered</span><h2 class="section-title" id="pvc-benefits">A practical option where resilience and maintainability matter.</h2><div class="service-benefits-grid"><div class="service-benefits-list"><?php foreach($benefits as $i=>[$t,$d]):?><article class="service-benefit"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div><div class="service-benefits-media service-technical-media" role="img" aria-label="Technical PVC flooring concept visual"></div></div></div></section>
<section class="section service-suitability" aria-labelledby="pvc-suitable"><div class="container"><span class="section-eyebrow">04 / Where it may be suitable</span><h2 class="section-title" id="pvc-suitable">Different rooms create different flooring priorities.</h2><p class="section-description">These are common discussion areas. Final suitability depends on the selected product, substrate and project specification.</p><div class="service-suitability-grid"><?php foreach($suitability as [$t,$d]):?><div class="service-suitability-item"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="pvc-assessment"><div class="container service-assessment-grid"><div><span class="section-eyebrow">05 / Assessment approach</span><h2 class="section-title" id="pvc-assessment">Plan from the substrate upward.</h2><p class="section-description">The quality of the finished installation depends heavily on the condition and preparation of the existing floor.</p></div><div class="service-assessment-steps"><?php foreach($assessment as $i=>[$t,$d]):?><article class="service-assessment-step"><span><?=sprintf('%02d',$i+1)?></span><div><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div></div></section>
<section class="section service-process" aria-labelledby="pvc-process"><div class="container"><span class="section-eyebrow">06 / Installation pathway</span><h2 class="section-title" id="pvc-process">From room assessment to clean handover.</h2><div class="service-process-grid"><?php foreach($process as [$n,$t,$d]):?><article class="service-process-item"><span><?=site_escape($n)?></span><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="pvc-care"><div class="container service-maintenance-grid"><div><span class="section-eyebrow">07 / Maintenance & care</span><h2 class="section-title" id="pvc-care">Care should match the selected floor and room use.</h2><p class="section-description">Cleaning chemicals, equipment, furniture protection and repair methods should follow the selected PVC flooring manufacturer's guidance.</p></div><div><div class="service-note-box">We avoid publishing universal wear, hygiene or slip-performance claims because those depend on the selected PVC product and its approved technical data.</div><div class="service-faq"><details><summary>Is PVC flooring suitable for every hospital or laboratory area?</summary><p>No. Room classification, cleaning, traffic and project requirements should be checked first.</p></details><details><summary>Can PVC be installed over an existing floor?</summary><p>Possibly, but only after the existing floor is assessed for flatness, soundness, moisture and compatibility with the installation method.</p></details><details><summary>Can different colours or zones be planned?</summary><p>Colour and layout can be discussed as part of the selected product range and project design.</p></details><details><summary>How long does installation take?</summary><p>Timing depends on preparation, area, product, access and site conditions, so it should be confirmed project by project.</p></details></div></div></div></section>
<section class="section service-final" aria-labelledby="pvc-final"><div class="container service-final-grid"><div><span class="section-eyebrow">08 / Start with the room</span><h2 class="section-title" id="pvc-final">Tell us how the space is used before selecting the floor.</h2></div><div><p>Share the room type, current floor, traffic, cleaning requirement and approximate area so the next step can be assessed.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>