<?php
$pageTitle = 'VDF Flooring Solutions';
$pageDescription = 'Explore VDF flooring for industrial concrete floors where flatness, finish, traffic and service requirements need to be considered together.';
$bodyClass = 'service-page service-vdf';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$problems=[['Uneven industrial floor','Flatness, local depressions and level differences can affect handling routes and later floor finishes.'],['Dusting / weak surface','The concrete surface condition should be understood before deciding on repair, topping or finishing requirements.'],['Heavy-use areas','Traffic, racks, material handling and equipment loads should be reviewed as part of the floor design.'],['New-floor planning','Levels, joints, curing, access and downstream operations need coordination before execution.']];
$benefits=[['Integrated concrete finish','VDF can be considered where the concrete slab and finished working surface are planned together.'],['Industrial-use planning','Traffic, equipment and operational routes can be considered during the floor design discussion.'],['Level / flatness focus','Floor level and flatness requirements can be defined against the intended use and project specification.'],['Future system readiness','Where later resin or other finishes are planned, the concrete floor condition can be coordinated with the downstream requirement.']];
$suitability=[['Manufacturing floors','Where concrete finish, traffic and equipment use need coordinated planning.'],['Warehouses','Where material movement and floor level requirements influence operations.'],['Logistics areas','Where handling routes and durability expectations need to be understood.'],['Industrial sheds','Where large-area concrete floor execution must be coordinated with construction sequencing.'],['Plant support areas','Where serviceability and practical floor finishing are important.'],['Project-specific slabs','Where the approved design calls for a defined VDF or industrial concrete-floor approach.']];
$assessment=[['Use & loading','Understand traffic, material handling, equipment and operational expectations.'],['Levels & flatness','Review the project requirement for levels, slope, flatness and interfaces.'],['Concrete / substrate scope','Confirm whether the work forms part of a new slab, topping, repair or existing-floor intervention.'],['Execution planning','Coordinate pours, joints, access, curing, protection and handover with the project schedule.']];
$process=[['01','Requirement review','Understand use, levels, traffic and project specification.'],['02','Area & level planning','Coordinate floor levels, joints, edges and interfaces.'],['03','Concrete placement','Execute the agreed concrete-floor scope and site controls.'],['04','Finishing process','Complete the specified finishing operation under controlled timing and conditions.'],['05','Curing & handover','Protect the floor, complete agreed curing and review the finished area.']];
?>
<main class="service-main" id="main-content">
<section class="service-hero" aria-labelledby="service-title"><div class="container-wide service-hero-grid"><div class="service-hero-copy"><span class="service-kicker">Flooring Solution / VDF</span><h1 id="service-title">VDF <em>Flooring</em></h1><p>An industrial concrete-flooring approach where slab condition, levels, flatness, traffic, finishing and execution planning need to work together.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="service-hero-note">Final concrete mix, thickness, reinforcement, hardener, flatness and performance criteria must follow the approved project design and specification.</p></div><div class="service-hero-media service-technical-media" role="img" aria-label="Technical industrial concrete flooring concept visual"><div class="service-hero-badge"><span>Plan the floor as infrastructure</span><strong>Use, levels, traffic, joints and execution sequence guide the approach.</strong></div></div></div></section>
<section class="section" aria-labelledby="what-is-vdf"><div class="container service-intro-grid"><div><span class="section-eyebrow">01 / What it is</span><h2 class="section-title" id="what-is-vdf">An industrial concrete floor planned around operation and finish.</h2></div><div class="service-copy"><p class="service-definition">VDF flooring is best treated as a <strong>concrete-floor execution system</strong> whose performance depends on the approved structural and floor specification.</p><p>The website therefore avoids inventing slab thickness, reinforcement, hardener dosage or flatness tolerances. Those values belong to the project design and agreed method.</p><p>Our focus is on assessing the use, levels, area, construction sequence and finished-floor requirement before execution planning.</p></div></div></section>
<section class="section service-problems" aria-labelledby="vdf-problems"><div class="container"><span class="section-eyebrow">02 / What to assess</span><h2 class="section-title" id="vdf-problems">The finished floor begins with planning the slab.</h2><div class="service-problem-grid"><?php foreach($problems as $i=>[$t,$d]):?><article class="service-problem"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="vdf-benefits"><div class="container"><span class="section-eyebrow">03 / Why it may be considered</span><h2 class="section-title" id="vdf-benefits">A working floor is part of the facility, not just its finish.</h2><div class="service-benefits-grid"><div class="service-benefits-list"><?php foreach($benefits as $i=>[$t,$d]):?><article class="service-benefit"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div><div class="service-benefits-media service-technical-media" role="img" aria-label="Technical VDF floor concept visual"></div></div></div></section>
<section class="section service-suitability" aria-labelledby="vdf-suitable"><div class="container"><span class="section-eyebrow">04 / Where it may be suitable</span><h2 class="section-title" id="vdf-suitable">Industrial spaces where the concrete floor carries the operation.</h2><p class="section-description">These are typical discussion areas. Final suitability and design parameters must come from the approved project requirement.</p><div class="service-suitability-grid"><?php foreach($suitability as [$t,$d]):?><div class="service-suitability-item"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="vdf-assessment"><div class="container service-assessment-grid"><div><span class="section-eyebrow">05 / Assessment approach</span><h2 class="section-title" id="vdf-assessment">Define how the floor will work before defining how it will be finished.</h2><p class="section-description">Traffic, loading, levels and construction sequencing need to be understood before an execution plan is meaningful.</p></div><div class="service-assessment-steps"><?php foreach($assessment as $i=>[$t,$d]):?><article class="service-assessment-step"><span><?=sprintf('%02d',$i+1)?></span><div><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div></div></section>
<section class="section service-process" aria-labelledby="vdf-process"><div class="container"><span class="section-eyebrow">06 / Execution pathway</span><h2 class="section-title" id="vdf-process">From project requirement to protected handover.</h2><div class="service-process-grid"><?php foreach($process as [$n,$t,$d]):?><article class="service-process-item"><span><?=site_escape($n)?></span><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="vdf-care"><div class="container service-maintenance-grid"><div><span class="section-eyebrow">07 / Care & downstream work</span><h2 class="section-title" id="vdf-care">Protect the new floor before it becomes an operational floor.</h2><p class="section-description">Curing, construction traffic, later installation work and any future coating system should be coordinated with the approved project method.</p></div><div><div class="service-note-box">We intentionally do not publish generic load capacity, thickness, reinforcement, flatness tolerance or hardener consumption. These are engineering/project parameters, not universal website values.</div><div class="service-faq"><details><summary>Is VDF suitable for every warehouse?</summary><p>No. Floor design depends on loading, racking, traffic, joints, slab design and project requirements.</p></details><details><summary>Can you give the floor thickness from the website?</summary><p>No. Thickness and reinforcement should come from the approved structural or flooring design.</p></details><details><summary>Can a resin coating be added later?</summary><p>Potentially, but the concrete condition, curing, moisture and preparation requirements for the later system must be considered.</p></details><details><summary>Can VDF be used to repair an old uneven floor?</summary><p>Repair or topping options depend on the existing slab condition, levels and engineering requirement and need site assessment.</p></details></div></div></div></section>
<section class="section service-final" aria-labelledby="vdf-final"><div class="container service-final-grid"><div><span class="section-eyebrow">08 / Start with the floor requirement</span><h2 class="section-title" id="vdf-final">Share the layout, use and project specification.</h2></div><div><p>We can review the area, operational use, levels, existing condition and execution constraints before discussing the flooring approach.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>