<?php
$pageTitle = 'Waterproofing Solutions';
$pageDescription = 'Explore waterproofing for roofs, wet areas, utility zones and selected structures. Akshaya reviews water entry, substrate condition, detailing and exposure before recommending an approach.';
$bodyClass = 'service-page service-waterproofing';
$assetPrefix = '..';
require __DIR__ . '/../includes/header.php';
$arrow = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
$visitUrl = site_escape(site_url('schedule-visit.php'));
$callUrl = site_escape('tel:+' . $siteConfig['phone_country_code'] . preg_replace('/\D+/', '', $siteConfig['phone']));
$problems=[['Visible leakage','The source and path of water entry should be understood before deciding how to treat the surface.'],['Cracks and junctions','Movement cracks, construction joints, corners, outlets and penetrations often need separate detailing.'],['Failed old treatment','Existing membranes or coatings may need investigation, repair or removal before a new system is applied.'],['Standing water / drainage','Slope, outlets and drainage condition can be as important as the waterproofing material itself.']];
$benefits=[['Cause-first approach','The site is reviewed for likely water-entry paths instead of simply covering the visible damp area.'],['Detail-led planning','Edges, joints, penetrations and termination points are considered as part of the system.'],['Substrate-specific preparation','Concrete condition, old coatings, cracks and repairs are assessed before application.'],['Maintenance visibility','Future inspection points and exposed areas can be considered during handover and maintenance planning.']];
$suitability=[['Roofs / terraces','Where exposure, slope, joints and drainage require assessment.'],['Wet areas','Where floor-to-wall interfaces, outlets and penetrations need coordinated detailing.'],['Utility areas','Where water exposure or leakage affects operational spaces.'],['Podiums / exposed slabs','Where surface condition and weather exposure influence the system.'],['Selected walls / external surfaces','Where the actual source and direction of moisture need to be confirmed.'],['Repair zones','Where an existing waterproofing treatment has locally failed or deteriorated.']];
$assessment=[['Leakage pattern','Review where water appears, when it occurs and what lies above or behind the affected area.'],['Substrate condition','Inspect cracks, joints, old coatings, repairs, surface strength and moisture.'],['Drainage & detailing','Check slope, outlets, penetrations, edges, corners and termination points.'],['System selection','Choose the waterproofing approach around exposure, substrate, access and project requirement.']];
$process=[['01','Site investigation','Understand leakage symptoms, exposure and surrounding construction.'],['02','Detail mapping','Identify cracks, joints, drains, penetrations and termination points.'],['03','Preparation & repair','Prepare the surface and complete agreed repairs before waterproofing.'],['04','System application','Apply the selected waterproofing treatment with required detailing.'],['05','Inspection & handover','Review completed details and discuss maintenance / observation points.']];
?>
<main class="service-main" id="main-content">
<section class="service-hero" aria-labelledby="service-title"><div class="container-wide service-hero-grid"><div class="service-hero-copy"><span class="service-kicker">Surface Protection / Waterproofing</span><h1 id="service-title">Waterproofing <em>Solutions</em></h1><p>A diagnosis-led approach for roofs, wet areas and selected structures where water entry, cracks, junctions, drainage and substrate condition need to be understood together.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Talk to Our Team <?= $arrow ?></a></div><p class="service-hero-note">The correct waterproofing approach depends on the source of water, construction detail, substrate and exposure.</p></div><div class="service-hero-media service-technical-media" role="img" aria-label="Technical waterproofing concept visual"><div class="service-hero-badge"><span>Find the path</span><strong>Leakage symptoms, cracks, joints, drainage and penetrations guide the diagnosis.</strong></div></div></div></section>
<section class="section" aria-labelledby="what-is-waterproofing"><div class="container service-intro-grid"><div><span class="section-eyebrow">01 / What it is</span><h2 class="section-title" id="what-is-waterproofing">Waterproofing starts by understanding how water is getting in.</h2></div><div class="service-copy"><p class="service-definition">A waterproofing system is only effective when the <strong>substrate and construction details</strong> are treated as part of the problem.</p><p>Visible dampness may not always be directly below the actual entry point. Cracks, joints, outlets, parapets, penetrations and failed old treatments can all influence the diagnosis.</p><p>For that reason, Akshaya's website positions waterproofing as a site-assessment service rather than a one-product answer.</p></div></div></section>
<section class="section service-problems" aria-labelledby="waterproofing-problems"><div class="container"><span class="section-eyebrow">02 / What to investigate</span><h2 class="section-title" id="waterproofing-problems">Treat the water path, not only the visible stain.</h2><div class="service-problem-grid"><?php foreach($problems as $i=>[$t,$d]):?><article class="service-problem"><span><?=sprintf('%02d',$i+1)?></span><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="waterproofing-benefits"><div class="container"><span class="section-eyebrow">03 / Why this approach matters</span><h2 class="section-title" id="waterproofing-benefits">Details usually decide whether the system succeeds.</h2><div class="service-benefits-grid"><div class="service-benefits-list"><?php foreach($benefits as $i=>[$t,$d]):?><article class="service-benefit"><span><?=sprintf('%02d',$i+1)?></span><div><h3><?=site_escape($t)?></h3><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div><div class="service-benefits-media service-technical-media" role="img" aria-label="Technical waterproofing detailing concept visual"></div></div></div></section>
<section class="section service-suitability" aria-labelledby="waterproofing-suitable"><div class="container"><span class="section-eyebrow">04 / Where it may be used</span><h2 class="section-title" id="waterproofing-suitable">Different structures expose water in different ways.</h2><p class="section-description">These are common assessment areas. The appropriate system depends on construction, exposure and the actual water-entry mechanism.</p><div class="service-suitability-grid"><?php foreach($suitability as [$t,$d]):?><div class="service-suitability-item"><strong><?=site_escape($t)?></strong><span><?=site_escape($d)?></span></div><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="waterproofing-assessment"><div class="container service-assessment-grid"><div><span class="section-eyebrow">05 / Assessment approach</span><h2 class="section-title" id="waterproofing-assessment">Map the problem before choosing the treatment.</h2><p class="section-description">The site visit should establish what is failing, where water may enter and how the area is constructed.</p></div><div class="service-assessment-steps"><?php foreach($assessment as $i=>[$t,$d]):?><article class="service-assessment-step"><span><?=sprintf('%02d',$i+1)?></span><div><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></div></article><?php endforeach;?></div></div></section>
<section class="section service-process" aria-labelledby="waterproofing-process"><div class="container"><span class="section-eyebrow">06 / Installation pathway</span><h2 class="section-title" id="waterproofing-process">From investigation to detailed application.</h2><div class="service-process-grid"><?php foreach($process as [$n,$t,$d]):?><article class="service-process-item"><span><?=site_escape($n)?></span><strong><?=site_escape($t)?></strong><p><?=site_escape($d)?></p></article><?php endforeach;?></div></div></section>
<section class="section" aria-labelledby="waterproofing-care"><div class="container service-maintenance-grid"><div><span class="section-eyebrow">07 / Maintenance & inspection</span><h2 class="section-title" id="waterproofing-care">Keep drainage and critical details visible.</h2><p class="section-description">Outlets, joints, exposed terminations and later penetrations should be monitored so new building work does not silently compromise the system.</p></div><div><div class="service-note-box">No waterproofing system should be presented as a universal permanent fix without understanding movement, drainage, substrate condition and construction details.</div><div class="service-faq"><details><summary>Can you waterproof only the visible leaking spot?</summary><p>Sometimes local repair may be appropriate, but the source and path of water should first be investigated because the visible leak can appear away from the entry point.</p></details><details><summary>Does standing water matter?</summary><p>Yes. Slope, outlets and drainage condition should be assessed because waterproofing and drainage work together.</p></details><details><summary>Can a new system go over an old membrane or coating?</summary><p>That depends on the existing material, adhesion, condition and compatibility. It should be assessed before deciding the preparation method.</p></details><details><summary>Can you guarantee the solution before a site visit?</summary><p>No. A meaningful recommendation requires site inspection and understanding of the construction and leakage pattern.</p></details></div></div></div></section>
<section class="section service-final" aria-labelledby="waterproofing-final"><div class="container service-final-grid"><div><span class="section-eyebrow">08 / Start with the leak</span><h2 class="section-title" id="waterproofing-final">Show us where and when the water appears.</h2></div><div><p>Share photographs, the affected area, when leakage occurs and any previous treatment. A site assessment can then determine the next step.</p><div class="service-hero-actions"><a class="btn btn-primary" href="<?= $visitUrl ?>">Schedule Site Visit <?= $arrow ?></a><a class="btn btn-outline" href="<?= $callUrl ?>">Call an Expert <?= $arrow ?></a></div></div></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>